### ISSUE TITLE
Don't leave styling for Phase 5

### ISSUE THREAD

**Issue by Chebotarev** [bencalabrese/pickup_tix#1]
You should be styling as you get through each phase. It doesn't have to be finished or fancy, but at every stage things should at least be positioned a little bit. I would account for some time during each phase for styling.

**Comment by bencalabrese** [comment]
Will do, I was feeling antsy about that anyway. I'll move up my styling for
the splash up one spot and add in some style after I get the credentials
set up. I was considering putting in placeholder divs for the components
that I haven't yet gotten to as well so that I can get an idea of the
overall shape of the app.

Best,
Ben Calabrese

**Comment by Chebotarev** [comment]
Sounds good. I would recommend though not spending too much time with the placeholders. It can get a little tricky to center and pad stuff correctly, and you don't want to get bogged down in something that's not going to be in the final product anyway
